const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let snapshot=null,baseline=null;
const pages={overview:["Alignment Overview","Live cross-check of baseline, admin, workspace, user, and persisted chat state."],matrix:["Differential Matrix","Filter and isolate expected-versus-observed configuration differences."],planes:["Plane Inspector","Sanitized REST telemetry and API coverage by origin plane."],baseline:["Baseline Contract","Version-controlled expected state and rule provenance."],export:["Export & Diagnostics","Read-only refresh and current sanitized snapshot exports."]};
const pretty=v=>JSON.stringify(v,null,2),toast=m=>{const x=$("#toast");x.textContent=m;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2600)};
async function api(path,opt={}){const r=await fetch(path,{cache:"no-store",headers:{"Content-Type":"application/json"},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||d.detail||`HTTP ${r.status}`);return d}
function busy(b,on,label="Working..."){if(on){b.dataset.old=b.textContent;b.textContent=label;b.disabled=true}else{b.textContent=b.dataset.old||b.textContent;b.disabled=false}}
function show(view){$$(".view").forEach(x=>x.classList.toggle("active",x.id===view));$$("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#page-title").textContent=pages[view][0];$("#page-desc").textContent=pages[view][1];localStorage.setItem("drift-view",view);if(view==="matrix")renderMatrix();if(view==="planes")renderPlanes();if(view==="baseline")loadBaseline();if(view==="export")$("#diagnostic-json").textContent=pretty(snapshot)}
const statusBadge=s=>`<span class="status ${esc(s)}">${esc(s)}</span>`,value=v=>`<div class="value">${esc(pretty(v))}</div>`;
function diffCard(d){return`<article class="diff-card"><div class="diff-top"><div><h4>${esc(d.label)}</h4><div class="diff-meta"><span>${esc(d.logical_path)}</span><span>${esc(d.parent_plane)} → ${esc(d.child_plane)}</span><span>${esc(d.entity_label)}</span></div></div>${statusBadge(d.status)}</div><p>${esc(d.recommendation||d.detail||"No action required.")}</p></article>`}
async function load(){snapshot=await api("/api/v1/snapshot");const o=snapshot.overview;$("#posture").textContent={aligned:"All observable enforced settings align",warning:"Overrides or drift require review",fail:"Critical configuration drift detected"}[o.status];$("#posture-badge").className=`status ${o.status}`;$("#posture-badge").textContent=o.status;$("#last-check").textContent=`Snapshot ${new Date(o.generated_at*1000).toLocaleTimeString()}`;$("#metrics").innerHTML=[["DRIFT",o.counts.drift],["OVERRIDES",o.counts.override],["ALIGNED",o.counts.aligned],["UNOBSERVABLE",o.counts.unobservable]].map(([l,v])=>`<article class="card"><strong>${v}</strong><span>${l}</span></article>`).join("");$("#plane-cards").innerHTML=o.planes.map(p=>`<article class="card" tabindex="0" data-tip="Latest independent ${esc(p.name)} plane poll."><header><strong>${esc(p.name.toUpperCase())}</strong>${statusBadge(p.status)}</header><p>${p.item_count} items · ${p.latency_ms} ms</p><span>${p.error?esc(p.error):`Observed ${new Date(p.observed_at*1000).toLocaleTimeString()}`}</span></article>`).join("");const issues=snapshot.diffs.filter(d=>["drift","override","unavailable"].includes(d.status)).slice(0,12);$("#priority").innerHTML=issues.length?issues.map(diffCard).join(""):'<div class="empty">No priority discrepancies.</div>';renderMatrix();renderPlanes();$("#diagnostic-json").textContent=pretty(snapshot)}
function renderMatrix(){if(!snapshot)return;const q=$("#search").value.toLowerCase(),plane=$("#plane-filter").value,status=$("#status-filter").value,severity=$("#severity-filter").value,issues=$("#issues-only").checked;const rows=snapshot.diffs.filter(d=>(!q||pretty(d).toLowerCase().includes(q))&&(!plane||d.parent_plane===plane||d.child_plane===plane)&&(!status||d.status===status)&&(!severity||d.severity===severity)&&(!issues||!["aligned","ignored"].includes(d.status)));$("#matrix-body").innerHTML=rows.map(d=>`<tr><td>${statusBadge(d.status)}<br><small>${esc(d.severity)}</small></td><td><strong>${esc(d.label)}</strong><br><small>${esc(d.logical_path)}</small></td><td>${esc(d.parent_plane)} → ${esc(d.child_plane)}</td><td>${esc(d.entity_label)}</td><td>${value(d.expected)}</td><td>${value(d.observed)}</td><td><button class="copy-row" data-copy="${snapshot.diffs.indexOf(d)}">Copy</button><br><small>${esc(d.recommendation)}</small></td></tr>`).join("");$("#matrix-empty").classList.toggle("hidden",rows.length>0)}
function renderPlanes(){if(!snapshot)return;$("#plane-inspector").innerHTML=Object.entries(snapshot.planes).map(([name,p])=>`<details class="diff-card"><summary>${statusBadge(p.status)} <strong>${esc(name.toUpperCase())}</strong> · ${p.item_count} items · ${p.latency_ms} ms</summary><p>${esc(p.error||"All configured API requests returned observable state.")}</p><pre>${esc(pretty(p.data))}</pre></details>`).join("")}
async function loadBaseline(){baseline=baseline||await api("/api/v1/baseline");$("#baseline-summary").innerHTML=[["RULES",baseline.rules.length],["SCHEMA",baseline.schema_version],["PRECEDENCE",baseline.metadata.precedence],["OVERRIDE POLICY",baseline.metadata.lower_plane_override_policy]].map(([l,v])=>`<article class="card"><strong>${esc(v)}</strong><span>${l}</span></article>`).join("");$("#baseline-json").textContent=pretty(baseline)}
async function refresh(b){busy(b,true,"Refreshing...");try{await api("/api/v1/refresh",{method:"POST"});await load();toast("Read-only refresh completed")}catch(e){toast(e.message)}finally{busy(b,false)}}
$("#nav").onclick=e=>e.target.dataset.view&&show(e.target.dataset.view);$("#refresh").onclick=()=>refresh($("#refresh"));$("#diagnostic-refresh").onclick=()=>refresh($("#diagnostic-refresh"));$("#copy-snapshot").onclick=()=>navigator.clipboard.writeText(pretty(snapshot)).then(()=>toast("Snapshot copied"));$("#matrix-body").onclick=e=>{if(e.target.dataset.copy===undefined)return;const d=snapshot.diffs[Number(e.target.dataset.copy)];navigator.clipboard.writeText(pretty(d)).then(()=>toast("Differential record copied"))};["search","plane-filter","status-filter","severity-filter","issues-only"].forEach(id=>$("#"+id).addEventListener(id==="search"?"input":"change",renderMatrix));
const tip=$("#tooltip");function showTip(x){tip.textContent=x.dataset.tip;tip.className="show";const r=x.getBoundingClientRect();tip.style.left=`${Math.min(innerWidth-320,r.left)}px`;tip.style.top=`${r.bottom+6}px`}document.body.addEventListener("mouseover",e=>{const x=e.target.closest("[data-tip]");if(x)showTip(x)});document.body.addEventListener("mouseout",e=>{if(e.target.closest("[data-tip]"))tip.className=""});document.body.addEventListener("focusin",e=>{const x=e.target.closest("[data-tip]");if(x)showTip(x)});document.body.addEventListener("focusout",()=>tip.className="");
const es=new EventSource("/api/v1/events");es.onopen=()=>{$("#event-dot").style.background="var(--ok)";$("#event-label").textContent="Live telemetry connected"};es.addEventListener("update",()=>load().catch(()=>{}));es.onerror=()=>{$("#event-dot").style.background="var(--warn)";$("#event-label").textContent="60-second fallback active"};setInterval(()=>load().catch(()=>{}),60000);show(localStorage.getItem("drift-view")||"overview");load().catch(e=>toast(e.message));
