const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let extractTool="deep", overview=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pretty=v=>JSON.stringify(v,null,2);
const toast=msg=>{const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2600)};
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await r.json().catch(()=>({error:{message:`HTTP ${r.status}`}}));if(!r.ok)throw new Error(data.error?.message||data.detail||`HTTP ${r.status}`);return data}
function busy(button,on,label="Working..."){if(on){button.dataset.label=button.textContent;button.textContent=label;button.disabled=true}else{button.textContent=button.dataset.label||button.textContent;button.disabled=false}}
function downloadJson(name,data){const url=URL.createObjectURL(new Blob([pretty(data)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function structuredResult(target,data,content=data.content||"",metadata=data.metadata||{}){target.className="result structured";target.innerHTML=`<div class="run-actions"><button class="secondary copy-structured">Copy JSON</button><button class="secondary download-structured">Download JSON</button></div><div class="tabs result-tabs"><button class="active" data-result-tab="rendered">Rendered</button><button data-result-tab="raw">Raw JSON</button><button data-result-tab="metadata">Metadata</button></div><div class="result-pane active" data-result-pane="rendered"><pre>${esc(content||"No rendered content returned.")}</pre></div><div class="result-pane" data-result-pane="raw"><pre>${esc(pretty(data))}</pre></div><div class="result-pane" data-result-pane="metadata"><pre>${esc(pretty(metadata))}</pre></div>`;target.querySelector(".copy-structured").onclick=()=>navigator.clipboard.writeText(pretty(data));target.querySelector(".download-structured").onclick=()=>downloadJson(`web-tools-${Date.now()}.json`,data);target.querySelector(".result-tabs").onclick=e=>{if(!e.target.dataset.resultTab)return;target.querySelectorAll("[data-result-tab]").forEach(x=>x.classList.toggle("active",x===e.target));target.querySelectorAll("[data-result-pane]").forEach(x=>x.classList.toggle("active",x.dataset.resultPane===e.target.dataset.resultTab))}}
function metric(value,label){return `<div class="metric"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function serviceCard(s){return `<article class="service-card"><header><h4>${esc(s.label)}</h4><span class="status ${esc(s.status)}">${esc(s.status)}</span></header><p>${esc(s.detail)}</p><div class="service-meta"><span>${esc(s.name)}</span><span>${esc(s.latency_ms)} ms</span></div></article>`}
function runCard(run,full=false){const steps=full?(run.steps||[]).map(s=>`<details class="step"><summary><span class="status ${esc(s.status)}">${esc(s.status)}</span> ${esc(s.label)}</summary><p>${esc(s.detail)}</p><pre>${esc(pretty(s.evidence))}</pre></details>`).join(""):"";return `<article class="run-card"><div class="run-top"><div><h4>${esc(run.kind||"validation_suite")}</h4><p>${new Date(run.started_at*1000).toLocaleString()} · ${esc(run.run_id)}</p></div><span class="status ${esc(run.status)}">${esc(run.status)}</span></div><p>${esc(pretty(run.summary||{}))}</p><div class="run-actions"><a href="/api/v1/diagnostics/runs/${encodeURIComponent(run.run_id)}/report?format=markdown">Download Markdown</a><a href="/api/v1/diagnostics/runs/${encodeURIComponent(run.run_id)}/report?format=json">Download JSON</a></div>${steps}</article>`}
async function loadOverview(){overview=await api("/api/v1/control/overview");$("#system-state").textContent=overview.summary.system_state;$("#metrics").innerHTML=[metric(`${overview.services.filter(s=>s.status==="reachable").length}/${overview.services.length}`,"Services connected"),metric(overview.capabilities.firecrawl_mode,"Firecrawl mode"),metric(overview.capabilities.prompt_lab?"Ready":"Unavailable","Prompt Lab"),metric(`${overview.summary.uptime_seconds}s`,"Monitor uptime")].join("");$("#services").innerHTML=overview.services.map(serviceCard).join("");$("#recent-runs").innerHTML=overview.recent_runs.length?overview.recent_runs.map(r=>runCard(r)).join(""):'<div class="empty">No durable runs yet.</div>';$("#last-updated").textContent=`Updated ${new Date().toLocaleTimeString()}`}
async function loadHistory(){const data=await api("/api/v1/diagnostics/runs");$("#history-runs").innerHTML=data.runs.length?data.runs.map(r=>runCard(r)).join(""):'<div class="empty">No runs recorded yet.</div>'}
async function loadPromptModels(){const p=await api("/api/v1/prompt/models");$("#prompt-badge").textContent=p.configured?"Ready":"Unavailable";$("#prompt-badge").className=`badge ${p.configured?"passed":"skipped"}`;$("#prompt-status").textContent=p.detail||"Server-side Open WebUI completion is ready.";$("#prompt-run").disabled=!p.configured;$("#prompt-model").innerHTML=(p.models.length?p.models:[{id:p.default_model_id,name:p.default_model_id}]).map(m=>`<option value="${esc(m.id)}" ${m.id===p.default_model_id?"selected":""}>${esc(m.name)}</option>`).join("")}
function show(view){$$(".view").forEach(v=>v.classList.toggle("active",v.id===view));$$("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("#page-title").textContent=$("#nav button.active").textContent;if(view==="history")loadHistory().catch(e=>toast(e.message));if(view==="prompt")loadPromptModels().catch(e=>toast(e.message));localStorage.setItem("control-view",view)}
$("#nav").addEventListener("click",e=>{if(e.target.dataset.view)show(e.target.dataset.view)});
$("#refresh").onclick=()=>loadOverview().catch(e=>toast(e.message));$("#history-refresh").onclick=()=>loadHistory().catch(e=>toast(e.message));
async function runSuite(button){busy(button,true,"Validating...");$("#suite-results").className="stack";$("#suite-results").innerHTML='<div class="panel">Running real checks. This can take a minute...</div>';try{const run=await api("/api/v1/diagnostics/runs",{method:"POST",body:JSON.stringify({query:$("#suite-query").value,extract_url:$("#suite-url").value,include_monitor:$("#suite-monitor").checked,prompt:$("#prompt-text").value,expected_text:[]})});$("#suite-results").innerHTML=runCard(run,true);toast(`Validation ${run.status}`);loadOverview()}catch(e){$("#suite-results").innerHTML=`<div class="result failed">${esc(e.message)}</div>`}finally{busy(button,false)}}
$("#run-suite").onclick=()=>runSuite($("#run-suite"));$("#run-suite-hero").onclick=()=>{show("validation");runSuite($("#run-suite"))};
$("#search-run").onclick=async()=>{const b=$("#search-run");busy(b,true,"Searching...");try{const d=await api("/web-tools/search",{method:"POST",body:JSON.stringify({query:$("#search-query").value})});$("#search-results").className="stack";$("#search-results").innerHTML=`<div class="run-actions"><button class="secondary search-copy">Copy JSON</button><button class="secondary search-download">Download JSON</button></div>`+(d.results.map(r=>`<article class="run-card"><h4><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a></h4><p>${esc(r.content)}</p><small>${esc(r.engine)} · ${esc(r.url)}</small></article>`).join("")||'<div class="empty">No results.</div>');$("#search-results .search-copy").onclick=()=>navigator.clipboard.writeText(pretty(d));$("#search-results .search-download").onclick=()=>downloadJson(`search-${Date.now()}.json`,d)}catch(e){toast(e.message)}finally{busy(b,false)}};
$("#extract-tabs").onclick=e=>{if(!e.target.dataset.tool)return;extractTool=e.target.dataset.tool;$$("#extract-tabs button").forEach(b=>b.classList.toggle("active",b===e.target));$("#extract-title").textContent=e.target.textContent+" extraction"};
$("#extract-run").onclick=async()=>{const b=$("#extract-run");busy(b,true,"Extracting...");const path={deep:"/web-tools/deep-web/extract",crawl:"/web-tools/crawl",firecrawl:"/web-tools/firecrawl"}[extractTool];try{const d=await api(path,{method:"POST",body:JSON.stringify({url:$("#extract-url").value})});structuredResult($("#extract-result"),d,d.content,d.metadata||{mode:d.mode,route:d.route,elapsed_ms:d.elapsed_ms})}catch(e){toast(e.message)}finally{busy(b,false)}};
$("#monitor-run").onclick=async()=>{const b=$("#monitor-run");if(!confirm("This may establish or update a semantic baseline. Continue?"))return;busy(b,true,"Evaluating...");try{const d=await api("/monitor/evaluate",{method:"POST",body:JSON.stringify({url:$("#monitor-url").value})});$("#monitor-result").className="result";$("#monitor-result").innerHTML=`<pre>${esc(pretty(d))}</pre>`}catch(e){toast(e.message)}finally{busy(b,false)}};
$("#prompt-run").onclick=async()=>{const b=$("#prompt-run");busy(b,true,"Verifying...");try{const d=await api("/api/v1/prompt/verify",{method:"POST",body:JSON.stringify({model_id:$("#prompt-model").value,prompt:$("#prompt-text").value,expected_text:$("#prompt-expected").value.split(",").map(x=>x.trim()).filter(Boolean),require_citations:$("#prompt-citations").checked,require_tool_call:$("#prompt-tools").checked})});structuredResult($("#prompt-result"),d,d.content,{passed:d.passed,model_id:d.model_id,latency_ms:d.latency_ms,expected_checks:d.expected_checks,citations:d.citations,tool_calls:d.tool_calls})}catch(e){toast(e.message)}finally{busy(b,false)}};
const es=new EventSource("/api/v1/control/events");es.onopen=()=>{$("#event-dot").style.background="var(--accent)";$("#event-label").textContent="Live updates connected"};es.addEventListener("update",()=>loadOverview().catch(()=>{}));es.onerror=()=>{$("#event-dot").style.background="var(--warn)";$("#event-label").textContent="Fallback refresh active"};
setInterval(()=>loadOverview().catch(()=>{}),60000);show(localStorage.getItem("control-view")||"overview");Promise.all([loadOverview(),loadPromptModels()]).catch(e=>toast(e.message));
